version: '3'


services:
  web:
    build: ./smartsanthe
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn smartsanthe.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./smartsanthe/:/usr/src/smartsanthe/
      - static_volume:/usr/src/smartsanthe/smartsanthe/static
    ports:
      - 8000:8000


  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/src/smartsanthe/smartsanthe/static
volumes:

  static_volume:
#    env_file:
#      - ./.env.dev
#services:
#  backend:
#    build:
#      context: ./smartsanthe
#    command: gunicorn smartsanthe.wsgi --bind 0.0.0.0:8000
#    ports:
#      - "8000:8000"
#
#