version: '3'


services:
  web:
    build: ./smartsanthe
#    command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn smartsanthe.wsgi --bind 0.0.0.0:8000
    volumes:
      - ./smartsanthe/:/smartsanthe/
      - static_volume:/smartsanthe/static
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    ports:
      - 1337:80
    volumes:
      - ./nginx/nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/smartsanthe/static


volumes:

  static_volume:
